RegisterNetEvent('ShowNotification')
AddEventHandler('ShowNotification', function(string)
    SetNotificationTextEntry("STRING")
    AddTextComponentString(string)
    DrawNotification(true, false)
end)